#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    lineFollowFWD,  sensorLineFollower)
#pragma config(Sensor, in2,    lineFollowCENTER, sensorLineFollower)
#pragma config(Sensor, in3,    lineFollowBACK, sensorLineFollower)
#pragma config(Sensor, in4,    lineFollowEnd,  sensorLineFollower)
#pragma config(Sensor, dgtl1,  inEncoder,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  bottomLimit,    sensorTouch)
#pragma config(Sensor, dgtl4,  lEncoder,       sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           rB,            tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port2,           lF,            tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port3,           rF,            tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port4,           lru,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           lrd,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           llu,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           lld,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           hook,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           in,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          lB,            tmotorVex393_HBridge, openLoop, encoderPort, I2C_4)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "gameAuto.h"

int rfMult = -1;
int lfMult = -1;
int encoderTicks = 392;

int deadZone = 15;

bool hasLockedIn = false;
float inKp = 5.5;
float inKi = 0.0;
float inKd = 0.0;
int ignoreInError = 1;
int inErrorMax = 40;
float integralIn = 0;
int prevErrorIn = 0;
int errorIn = 0;

bool hasLockedLift = false;
float liftKp = 3.5;
float liftKi = 0.0;
float liftKd = 0.0;
int ignoreliftError = 1;
int liftErrorMax = 40;
float integralLift = 0;
int prevErrorLift = 0;
int errorLift = 0;

float driveKp = 1.0;
float driveKi = 0.0;
float driveKd = 0.0;

float fwd=0;
float strafe=0;
float clockwise=0;

int ignoreDriveError = 1;
int driveErrorMax = 20;

float integralLF = 0;
float integralLB = 0;
float integralRF = 0;
float integralRB = 0;

int prevErrorLF = 0;
int prevErrorLB = 0;
int prevErrorRF = 0;
int prevErrorRB = 0;

int tickIncrease = 20;
int inTarget = SensorValue[inEncoder];
//Reset All Encoder
double lx() {
	return (vexRT[ch4]^3)/(127^2);
}
double ly() {
	return (vexRT[ch3]^3)/(127^2);
}
double rx() {
	return (vexRT[ch1]^3)/(127^2);
}
void clearEncoders () {
	nMotorEncoder[rB] = 0;
	nMotorEncoder[rF] = 0;
	nMotorEncoder[lF] = 0;
	nMotorEncoder[lB] = 0;
	sensorValue[lEncoder] = 0;
}
void inPo (int power) {
	motor[in] = power;
}

//Set Arm Power
void armPo(int power) {
	motor[lru] = motor[lrd] = motor[llu] = motor[lld] = power;
}

//Set target value in ticks
void driveTicks(int fwdDrive, int rDrive, int rotateDrive)
{
	fwd = fwdDrive*sqrt(2);
	strafe = rDrive*sqrt(2);
	clockwise = rotateDrive*sqrt(2);
}

//Set drive target in inches
void driveIn(int fwdDrive, int rDrive, int rotateDrive)
{
	float fakefwd = (fwdDrive*sqrt(2)*4*PI)/encoderTicks;
	float fakeright = (rDrive*sqrt(2)*4*PI)/encoderTicks;
	fwd = fakefwd;
	strafe = fakeright;
	clockwise = rotateDrive;
}

void setHook(int po) {
		motor[hook] = po;
}

int errorRB;
int errorLB;
int errorRF;
int errorLF;
//PID for drive
task drivePID() {
	while(true) {
		int ticksRF = nMotorEncoder[rF];
		int ticksLB = nMotorEncoder[lB];
		int ticksLF = nMotorEncoder[lF];
		int ticksRB = nMotorEncoder[rB];

		int targetRB = fwd - clockwise + strafe;
		int targetLB = fwd + clockwise - strafe;
		int targetRF = fwd - clockwise - strafe;
		int targetLF = fwd + clockwise + strafe;

		errorRB = targetRB + ticksRB;
		errorLB = targetLB - ticksLB;
		errorRF = targetRF + ticksRF;
		errorLF = targetLF - ticksLF;

		integralRB = errorRB;
		integralLB = errorLB;
		integralRF = errorRF;
		integralLF = errorLF;

		if(abs(integralRB) < ignoreDriveError) {
			integralRB = 0;
		}
		if(abs(integralRB) > driveErrorMax) {
			integralRB = 0;
		}


		if(abs(integralRF) < ignoreDriveError) {
			integralRF = 0;
		}
		if(abs(integralRF) > driveErrorMax) {
			integralRF = 0;
		}


		if(abs(integralLB) < ignoreDriveError) {
			integralLB = 0;
		}
		if(abs(integralLB) > driveErrorMax) {
			integralLB = 0;
		}


		if(abs(integralLF) < ignoreDriveError) {
			integralLF = 0;
		}
		if(abs(integralLF) > driveErrorMax) {
			integralLF = 0;
		}

		int derivativeRF = errorRF - prevErrorRF;
		int derivativeRB = errorRB - prevErrorRB;
		int derivativeLF = errorLF - prevErrorLF;
		int derivativeLB = errorLB - prevErrorLB;

		prevErrorRF = errorRF;
		prevErrorRB = errorRB;
		prevErrorLB = errorLB;
		prevErrorLF = errorLF;
		writeDebugStreamLine("%f,%f",-1*(driveKp * errorLF + driveKi * integralLF + driveKd * derivativeLF), -1*(driveKp * errorRF + driveKi * integralRF + driveKd * derivativeRF));
		motor[rF] = (driveKp * errorRF + driveKi * integralRF + driveKd * derivativeRF);
		motor[rB] = (driveKp * errorRB + driveKi * integralRB + driveKd * derivativeRB);
		motor[lF] = (driveKp * errorLF + driveKi * integralLF + driveKd * derivativeLF);
		motor[lB] = (driveKp * errorLB + driveKi * integralLB + driveKd * derivativeLB);
	}
}
int ticksIn = SensorValue[inEncoder];
//PID for intake
task intakePID() {
	while(true) {
		ticksIn = SensorValue[inEncoder];
		errorIn = inTarget - ticksIn;
		integralIn = errorIn;

		if(abs(integralIn) < ignoreDriveError) {
			integralIn = 0;
		}
		if(abs(integralIn) > driveErrorMax) {
			integralIn = 0;
		}
		int derivativeIn = errorIn - prevErrorIn;

		prevErrorIn = errorIn;

		motor[in] = (inKp * errorIn + inKi * integralIn + inKd * derivativeIn);

	}
}
int ticksLift;
int liftTarget = SensorValue[lEncoder];
//PID for intake
task armPID() {
	while(true) {
		ticksLift = SensorValue[lEncoder];
		errorLift = liftTarget - ticksLift;
		integralLift = errorLift;

		if(abs(integralLift) < ignoreDriveError) {
			integralLift = 0;
		}
		if(abs(integralLift) > driveErrorMax) {
			integralLift = 0;
		}
		int derivativeLift = errorLift - prevErrorLift;

		prevErrorLift = errorLift;

		armPo(liftKp * errorLift + liftKi * integralLift + liftKd * derivativelift);

	}
}
void encoderClear () {
	nMotorEncoder[lF] = 0;
	nMotorEncoder[lB] = 0;
	nMotorEncoder[rB] = 0;
	nMotorEncoder[rF] = 0;
}

//HI MIGGY
/**************************AUTO*******************************************************/
void redCube () {
	while(SensorValue[lEncoder] > -660) {
		armPo(127);
	}
	armPo(0);
	clockwise=-370;
	/*fwd=-85;
	strafe = -85;
	wait1Msec(1000);
	//clockwise=-130;
	wait1Msec(700);
	fwd=-200;
	clockwise=-130;
	//strafe=75;
	wait1Msec(700);*/
	wait1Msec(2000);
	fwd=-100;
	while(SensorValue[lEncoder] < -50) {
		armPo(-127);
	}
	armPo(-10);
	fwd = 200;
	wait1Msec(1000);
	clockwise=200;
	wait1Msec(1000);
	fwd=1500;
	wait1Msec(1000);
	inPo(127);
	wait1Msec(500);
	inPo(0);
}
/**************************AUTO*******************************************************/

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	startTask(drivePID);
	redCube();
	//startTask(drivePID);
	//driveIn(10, 0, 0);
	//strafe = -125;
	//stopTask(drivePID);
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User CodriveInol Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////
int battVoltage;

task usercontrol()
{
	// User control code here, inside the loop
	clearEncoders();
	rfMult = 1;
	lfMult = 1;
	//startTask(drivePID);
	startTask(intakePID);
	//startTask(armPID);

	while (true)
	{
		battVoltage = nImmediateBatteryLevel/1000.0;

		/*if(abs(vexRT[Ch3]) < deadZone && abs(vexRT[Ch4]) < deadZone && abs(vexRT[Ch1]) < deadZone)
		{
			fwd = 0;
			strafe = 0;
			clockwise = 0;
		}
		else {
			motor[rB] = vexRT[Ch3] - vexRT[Ch1] + vexRT[Ch4];
			motor[lB] = vexRT[Ch3] + vexRT[Ch1] - vexRT[Ch4];
			motor[rF] = vexRT[Ch3] - vexRT[Ch1] - vexRT[Ch4];
			motor[lF] = vexRT[Ch3] + vexRT[Ch1] + vexRT[Ch4];
		}*//*
		if(abs(vexRT[Ch3]) > deadZone)
		{
			fwd = vexRt[Ch3];
		}
		else {
			fwd = 0;
			nMotorEncoder[lB] = 0;
			nMotorEncoder[lF] = 0;
			nMotorEncoder[rB] = 0;
			nMotorEncoder[rF] = 0;
		}
		if(abs(vexRT[Ch4]) > deadZone)
		{
			strafe = vexRt[Ch4];
		}
		else {
			strafe = 0;
			nMotorEncoder[lB] = 0;
			nMotorEncoder[lF] = 0;
			nMotorEncoder[rB] = 0;
			nMotorEncoder[rF] = 0;
		}
		if(abs(vexRT[Ch1]) > deadZone)
		{
			clockwise =  vexRt[Ch1];
		}
		else {
			clockwise = 0;
			nMotorEncoder[lB] = 0;
			nMotorEncoder[lF] = 0;
			nMotorEncoder[rB] = 0;
			nMotorEncoder[rF] = 0;
		}*/

		motor[rB] = vexRT[Ch3] - vexRT[Ch1] + vexRT[Ch4];
		motor[lB] = vexRT[Ch3] + vexRT[Ch1] - vexRT[Ch4];
		motor[rF] = vexRT[Ch3] - vexRT[Ch1] - vexRT[Ch4];
		motor[lF] = vexRT[Ch3] + vexRT[Ch1] + vexRT[Ch4];

		if(vexRT[Btn5U] == 1) {
			armPo(127);
		}
		else if(vexRT[Btn5D] == 1) {
			armPo(-127);
		}
		else {
			armPo(0);
		}
		if(vexRT[Btn8L] == 1) {
			motor[hook] = 127/3;
		}
		else if(vexRT[Btn8R] == 1) {
			motor[hook] = -127/3;
		}
		else {
			motor[hook] = 0;
		}

		if(vexRT[Btn6U] == 1) {
			inTarget = ticksIn + tickIncrease;
			hasLockedIn = false;
		}
		else if(vexRT[Btn6D] == 1) {
			inTarget = ticksIn - tickIncrease;
			hasLockedIn = false;
		}
		else if(!hasLockedIn) {
			inTarget = ticksIn;
			hasLockedIn = true;
		}/*
		if(vexRT[Btn5U] == 1) {
			liftTarget = ticksLift + tickIncrease;
			hasLockedLift = false;
		}
		else if(vexRT[Btn5D] == 1) {
			LiftTarget = ticksLift - tickIncrease;
			hasLockedLift = false;
		}
		else if(!hasLockedLift) {
			liftTarget = ticksLift;
			hasLockedLift = true;
		}*/
		//Simple PID free drive for testing
		/*
		motor[rB] = fwd - clockwise + strafe;
		motor[lB] = fwd + clockwise - strafe;
		motor[rF] = fwd - clockwise - strafe;
		motor[lF] = fwd + clockwise + strafe;
		/**/
	}
}
