#pragma config(Sensor, dgtl1,  rDriveEncoder,  sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rLiftEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  lDriveEncoder,  sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  lLiftEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           driveLB,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           driveLF,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           liftLB,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           liftLT,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           intakeR,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           intakeL,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           liftRT,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           liftRB,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           driveRF,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          driveRB,       tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

float ignoreDriveError = 40;
float driveKp = 1.5;
float driveKi = 0.0;
float driveKd = 0.0;

float ignoreArmError = 40;
float armKp = 10.0;
float armKi = 0.0;
float armKd = 0.0;

bool toDriveStream = false;
float rPrevError = 0;
float rIntegral = 0;
float lPrevError = 0;
float lIntegral = 0;
float rError;
float lError;
float lDerivative;
float rDerivative;
float driveSetLPt = 0;
float driveSetRPt = 0;

bool toArmStream = false;
float rAPrevError = 0;
float rAIntegral = 0;
float lAPrevError = 0;
float lAIntegral = 0;
float rAError;
float lAError;
float lADerivative;
float rADerivative;
float liftSetPt = 0;
float lastLiftSetPt = 0;

void init() {
	SensorValue[rLiftEncoder] = 0;
	SensorValue[lLiftEncoder] = 0;
	SensorValue[rDriveEncoder] = 0;
	SensorValue[lDriveEncoder] = 0;
}

task armPID() {
	while(true) {
		rAError = liftSetPt + SensorValue[rLiftEncoder];
		lAError = liftSetPt - SensorValue[lLiftEncoder];
		lAIntegral += lAError;
		rAIntegral += rAError;
		rADerivative = rAError - rAPrevError;
		lDerivative = lAError - lAPrevError;
		motor[liftLB] = (armKp*lAError) + (armKi*lAIntegral) + (armKd*lADerivative);
		motor[liftLT] = (armKp*lAError) + (armKi*lAIntegral) + (armKd*lADerivative);
		motor[liftRB] = (armKp*RAError) + (armKi*RAIntegral) + (armKd*RADerivative);
		motor[liftRT] = (armKp*RAError) + (armKi*RAIntegral) + (armKd*RADerivative);
		if(toArmStream) {
			writeDebugStreamLine("%f, %f,",lAError, rAError);
		}
	}
}

task drivePID() {
	while(true) {
		rError = driveSetRPt + SensorValue[rDriveEncoder];
		lError = driveSetLPt - SensorValue[lDriveEncoder];
		lIntegral += lError;
		rIntegral += rError;
		rDerivative = rError - rPrevError;
		lDerivative = lError - lPrevError;
		motor[driveRB] = (driveKp*rError) + (driveKi*rIntegral) + (driveKd*rDerivative);
		motor[driveRF] = (driveKp*rError) + (driveKi*rIntegral) + (driveKd*rDerivative);
		motor[driveLB] = (driveKp*lError) + (driveKi*lIntegral) + (driveKd*lDerivative);
		motor[driveLF] = (driveKp*lError) + (driveKi*lIntegral) + (driveKd*lDerivative);
		if(toDriveStream) {
			writeDebugStreamLine("%f, %f,", rError, lError);
		}
	}
}

void setDrive(int left, int right) {
	motor[driveLB] = motor[driveLF] = left;
	motor[driveRB] = motor[driveRF] = right;
}

void driveStream(bool set) {
	toDriveStream = set;
}

void armStream(bool set)
{
	toArmStream = set;
}

void driveTicks(float ticks) {
	driveSetRPt += ticks;
	driveSetLPt += ticks;
}

void turnTicks(float ticks) {
	driveSetRPt -= ticks;
	driveSetLPt += ticks;
}

void intake(int po) {
	motor[intakeR] = -po;
	motor[intakeL] = po;
}

void armControl() {
	if(vexRT[Btn6D]) {
		liftSetPt = SensorValue[lLiftEncoder] + 40;
	}
	else if(vexRT[Btn6U]) {
		liftSetPt = SensorValue[lLiftEncoder] - 40;
	}
	else {
		liftSetPt = SensorValue[lLiftEncoder] - 3;
	}
}

void driveControl(float leftPo, float rightPo) {
	motor[driveRB] = rightPo;
	motor[driveRF] = rightPo;
	motor[driveLB] = leftPo;
	motor[driveLF] = leftPo;
}

void pre_auton()
{
  bStopTasksBetweenModes = true;
}

void intakePo(float po) {
	motor[intakeL] = motor[intakeR] = po;
}

task autonomous()
{
	init();
	startTask(drivePID);
	//driveStream(true);
	driveTicks(360);
	stopTask(drivePID);
}

task usercontrol()
{
	init();
	while (true)
	{

		startTask(armPID);
		//armStream(true);
		driveControl(vexRt[Ch3] + vexRT[Ch1], vexRT[Ch3] - vexRT[Ch1]);
		armControl();
		//liftSetPt = -15;
	}
}
